apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - command:
       - sh
       - -c
       - 'date >> /mnt/openebs-csi/date.txt; hostname >> /mnt/openebs-csi/hostname.txt; sync; sleep 5; sync; tail -f /dev/null;'
    image: busybox
    imagePullPolicy: Always
    name: busybox
    volumeMounts:
    - mountPath: /mnt/openebs-csi
      name: demo-vol
  volumes:
  - name: demo-vol
    persistentVolumeClaim:
      claimName: demo-csivol-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-csivol-claim
spec:
  storageClassName: openebs-csi-cstor-sparse
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
