kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: openebs-csi-cstor-sparse
provisioner: openebs-csi.openebs.io
allowVolumeExpansion: true
parameters:
  replicaCount: "1"
  storagePoolClaim: cstor-sparse-pool
