apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: demo-snapshot
spec:
  snapshotClassName: csi-cstor
  source:
    name: demo-csivol-claim
    kind: PersistentVolumeClaim
